rootProject.name = "kanbanana"

include("auth-service")
include("user-service")
include("document-service")
include("kanban-service")
include("search-service")
include("notification-service")
include("bootstrap-auth-service")
include("bootstrap-user-service")
include("bootstrap-document-service")
include("bootstrap-kanban-service")
include("bootstrap-search-service")
include("bootstrap-notification-service")
include("api-gateway")
include("common-library")
